version: "3.9"
services:
  vertica:
    container_name: vertica-ce
    image: vertica/vertica-ce
    env_file: .env
    ports:
      - "5433:5433"
      - "5444:5444"
    deploy:
      mode: global
    volumes:
      - type: volume
        source: vertica-data
        target: /data

volumes:
  vertica-data:
