-- RESOURCE POOL
CREATE RESOURCE POOL etl_pool EXECUTIONPARALLELISM 8 MAXCONCURRENCY 5 MEMORYSIZE '4000M' MAXMEMORYSIZE '60%' PRIORITY 10 CPUAFFINITYSET '50%';
ALTER RESOURCE POOL etl_pool CPUAFFINITYMODE SHARED CPUAFFINITYSET '50%';
ALTER RESOURCE POOL etl_pool MAXQUERYMEMORYSIZE '14G';
ALTER RESOURCE POOL etl_pool MAXMEMORYSIZE '14G';
ALTER RESOURCE POOL etl_pool MEMORYSIZE '0%';

GRANT USAGE ON RESOURCE POOL etl_pool to etl_vsql;

ALTER USER etl_vsql RESOURCE POOL etl_pool;

SELECT * FROM RESOURCE_POOLS ;
SELECT * FROM MEMORY_USAGE ORDER BY start_time;
